[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["F"]

[tool.isort]
py_version=39
skip=["backendev/*", ".gitignore", ".ruff", ".idea", "db.sqlite3"]

[settings]
profile = "django"
src_path = ["isort"]