[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["F"]

[tool.isort]
py_version=39
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
virtual_env = "venv"
skip=["backendev/*", ".gitignore", ".ruff_cache", ".idea", "db.sqlite3"]

[tool.black]
line-length = 120
target-version = ['py311']
preview = true
include = '\.pyi?$'
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | backendev
    | __pycache
  )/
'''
