# Generated by Django 4.2.7 on 2023-11-23 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('gender', models.CharField(default=None, max_length=10, null=True)),
                ('email', models.EmailField(default=None, max_length=225, unique=True)),
                ('employment_start', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
                ('employee_address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.address')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('employment_term', models.CharField(default=3, max_length=1)),
                ('position', models.CharField(choices=[('1', 'Engineer'), ('2', 'Manager'), ('3', 'Accountant'), ('4', 'HR'), ('5', 'Sales'), ('6', 'IT')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=1)),
                ('employment_type', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Contractual'), ('4', 'Internship'), ('5', 'Casual')], default='2', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.FloatField(default=0, null=True)),
                ('net_salary', models.FloatField(default=0, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('last_payment', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_days', models.IntegerField(default=0, null=True)),
                ('sick_days', models.IntegerField(default=14, null=True)),
                ('agreed_salary', models.FloatField(default=None, null=True)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employmentstatus'),
        ),
    ]
