# Generated by Django 4.2.7 on 2025-09-23 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_name", models.CharField(default=None, max_length=225, null=True)),
                ("client_email", models.EmailField(default=None, max_length=225, null=True)),
                ("client_contact", models.IntegerField(default=None, null=True)),
                ("client_details", models.JSONField(default=None, null=True)),
                ("last_invoiced", models.DateField(default=None, null=True)),
                ("is_client_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_address",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="locations.address"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("billed_hours", models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ("approved_hours", models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True)),
                ("job_detail", models.CharField(default=None, max_length=255, null=True)),
                ("additional_details", models.JSONField(null=True)),
                ("rate", models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="worklogs.clients"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.CreateModel(
            name="Worklogs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("worklog_date", models.DateField(default=None, null=True)),
                ("start_time", models.TimeField(default=None, null=True)),
                ("end_time", models.TimeField(default=None, null=True)),
                ("break_time", models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ("description", models.CharField(default=None, max_length=255, null=True)),
                ("worklog_billed", models.BooleanField(default=False)),
                ("worklog_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worklog_type",
                    models.CharField(
                        choices=[("Worklog", "Worklog"), ("LeaveLog", "Leavelog")], default="Worklog", max_length=20
                    ),
                ),
                (
                    "worklog_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Billed", "Billed")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Job",
                        to="worklogs.jobs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worklog",
                "verbose_name_plural": "Worklogs",
            },
        ),
    ]
