# Generated by Django 4.2.7 on 2025-09-23 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("city_name", models.CharField(default=None, max_length=225, null=True)),
                ("state", models.CharField(default=None, max_length=100, null=True)),
                ("state_code", models.CharField(default=None, max_length=4, null=True)),
                ("has_branch", models.BooleanField(default=False, null=True)),
                ("postal_code", models.CharField(default=None, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("country_name", models.CharField(default=None, max_length=225, null=True)),
                ("country_code", models.CharField(default=None, max_length=3, null=True)),
                ("phone_code", models.CharField(default=None, max_length=4, null=True)),
                ("currency", models.CharField(default=None, max_length=4, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("address", models.CharField(default=None, max_length=225, null=True)),
                ("lat", models.FloatField(default=0.0, null=True)),
                ("lng", models.FloatField(default=0.0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_city_id",
                        to="locations.city",
                    ),
                ),
                (
                    "country_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_country_id",
                        to="locations.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
